
import React, { useState } from 'react';
import { SpecificationItem, MaterialTier } from '../types';
import { Download, RefreshCw, ShoppingCart, Tag } from 'lucide-react';
import { useProject } from '../context/ProjectContext';
import { calculateMaterials } from '../utils/materialCalculator';

interface SpecificationTableProps {
  items: SpecificationItem[];
}

const SpecificationTable: React.FC<SpecificationTableProps> = ({ items }) => {
  const { 
    updateSpecificationItem, 
    setSpecification, // Access to overwrite list
    panelConfig,
    floorPlanElements,
    cableRuns
  } = useProject();

  const [tier, setTier] = useState<MaterialTier>('standard');
  const [isSyncing, setIsSyncing] = useState(false);

  const totalCost = items.reduce((sum, item) => sum + ((item.quantity * (item.estimatedPrice || 0))), 0);

  const handleSync = () => {
    setIsSyncing(true);
    // 1. Generate new items
    const newItems = calculateMaterials(panelConfig, floorPlanElements, cableRuns, tier);
    
    // 2. Keep "manual" items that user added (not auto-generated)
    const manualItems = items.filter(i => !i.isAutoGenerated);
    
    // 3. Merge
    // Note: We completely replace old auto-gen items with new ones to avoid duplicates on re-calc
    setTimeout(() => {
        setSpecification([...manualItems, ...newItems]);
        setIsSyncing(false);
    }, 500); // Fake delay for UX
  };

  const handleDownloadCSV = () => {
    const BOM = "\uFEFF";
    const headers = "Категория;Наименование;Модель;Ед.изм.;Кол-во;Цена;Сумма";
    const rows = items.map(item => {
      const sum = item.quantity * (item.estimatedPrice || 0);
      return `${item.category};${item.name};${item.model || ''};${item.unit};${item.quantity};${item.estimatedPrice};${sum}`;
    }).join("\n");

    const csvContent = BOM + headers + "\n" + rows;
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", "specification.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-4">
      {/* Toolbar */}
      <div className="flex flex-col md:flex-row justify-between items-center bg-white p-4 rounded-xl border border-slate-200 shadow-sm gap-4 print:hidden">
         <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 text-slate-700 font-medium">
               <ShoppingCart className="w-5 h-5 text-blue-600"/>
               <span>Смета материалов</span>
            </div>
            
            <div className="h-6 w-px bg-slate-200"></div>

            <div className="flex items-center gap-2">
               <Tag className="w-4 h-4 text-slate-400"/>
               <select 
                 value={tier} 
                 onChange={(e) => setTier(e.target.value as MaterialTier)}
                 className="bg-slate-50 border border-slate-200 rounded-lg text-sm px-3 py-1.5 focus:ring-2 focus:ring-blue-500 outline-none cursor-pointer hover:bg-slate-100 transition-colors"
               >
                 <option value="budget">Бюджет (IEK/TDM)</option>
                 <option value="standard">Стандарт (Schneider/Systeme)</option>
                 <option value="premium">Премиум (ABB/Legrand)</option>
               </select>
            </div>
         </div>

         <div className="flex items-center gap-3">
            <button 
              onClick={handleSync}
              disabled={isSyncing}
              className={`
                flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all
                ${isSyncing ? 'bg-slate-100 text-slate-400' : 'bg-blue-600 text-white hover:bg-blue-700 shadow-lg shadow-blue-200'}
              `}
            >
              <RefreshCw className={`w-4 h-4 ${isSyncing ? 'animate-spin' : ''}`} />
              {isSyncing ? 'Считаю...' : 'Пересчитать по проекту'}
            </button>
            <button 
              onClick={handleDownloadCSV}
              className="flex items-center gap-2 text-slate-600 hover:text-blue-600 text-sm font-medium border border-slate-200 px-3 py-2 rounded-lg hover:bg-slate-50 transition-colors"
            >
              <Download className="w-4 h-4" />
              CSV
            </button>
         </div>
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="bg-slate-50 text-slate-500 font-medium border-b border-slate-100 print:bg-white print:text-black print:border-black">
              <tr>
                <th className="px-6 py-4">Наименование</th>
                <th className="px-6 py-4">Артикул / Модель</th>
                <th className="px-6 py-4">Ед.</th>
                <th className="px-6 py-4 text-right">Кол-во</th>
                <th className="px-6 py-4 text-right">Цена</th>
                <th className="px-6 py-4 text-right">Сумма</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 print:divide-black">
              {items.length === 0 ? (
                 <tr>
                    <td colSpan={6} className="text-center py-10 text-slate-400">
                       <div className="flex flex-col items-center gap-2">
                         <ShoppingCart className="w-8 h-8 opacity-20"/>
                         <p>Список пуст. Нажмите "Пересчитать по проекту", чтобы собрать смету автоматически.</p>
                       </div>
                    </td>
                 </tr>
              ) : (
                items.map((item) => (
                  <tr key={item.id} className="hover:bg-slate-50/50 print:hover:bg-transparent">
                    <td className="px-6 py-4 font-medium text-slate-900">
                      <div className="flex flex-col">
                        <span>{item.name}</span>
                        <span className="text-[10px] text-slate-400 uppercase tracking-wider">{item.category}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-slate-600 font-mono text-xs">{item.model || '-'}</td>
                    <td className="px-6 py-4 text-slate-600">{item.unit}</td>
                    <td className="px-6 py-4 text-right font-medium">{item.quantity}</td>
                    <td className="px-6 py-4 text-right text-slate-500 w-32">
                      <div className="flex justify-end gap-1 items-center">
                        <input 
                          type="number"
                          value={item.estimatedPrice || 0}
                          onChange={(e) => updateSpecificationItem(item.id, { estimatedPrice: Number(e.target.value) })}
                          className="w-24 text-right bg-transparent border-b border-transparent hover:border-slate-200 focus:border-blue-500 outline-none transition-colors"
                        />
                        <span className="text-xs">₽</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-right font-medium text-slate-900">
                      {(item.quantity * (item.estimatedPrice || 0)).toLocaleString()} ₽
                    </td>
                  </tr>
                ))
              )}
            </tbody>
            {items.length > 0 && (
              <tfoot className="bg-slate-50 border-t border-slate-200 print:bg-white print:border-black">
                <tr>
                  <td colSpan={5} className="px-6 py-4 text-right font-bold text-slate-900">Итого сметная стоимость:</td>
                  <td className="px-6 py-4 text-right font-bold text-blue-600 text-lg">{totalCost.toLocaleString()} ₽</td>
                </tr>
              </tfoot>
            )}
          </table>
        </div>
      </div>
    </div>
  );
};

export default SpecificationTable;
