
export enum ToolType {
  LOAD_ANALYZER = 'load_analyzer',
  COMPONENT_SELECTOR = 'component_selector',
  COMPLIANCE_CHECKER = 'compliance_checker',
  PHASE_BALANCER = 'phase_balancer',
  CONDUIT_CALCULATOR = 'conduit_calculator',
  GROUNDING_CALCULATOR = 'grounding_calculator'
}

export interface LoadItem {
  id: string;
  name: string;
  power: number; // kW
  count: number;
  category: 'lighting' | 'socket' | 'heavy' | 'hvac';
  phase?: 'L1' | 'L2' | 'L3' | 'ABC'; // Phase assignment
}

export interface AnalysisResult {
  totalInstalledPower: number; // Pi (kW)
  designPower: number; // Pp (kW)
  designCurrent: number; // Ip (A)
  powerFactor: number; // cos phi
  demandFactor: number; // Kc
  recommendations: string[];
  suggestedGroups: {
    name: string;
    load: number;
    breaker: string;
    cable: string;
  }[];
}

export interface DeratingFactors {
  tempCoeff: number; // K1: Ambient temperature (1.0 for 25C)
  groupCoeff: number; // K2: Grouping (0.8 for bundle of 3)
}

export interface ComponentRequest {
  loadCurrent: number; // Amps
  length: number; // Meters
  installationMethod: 'hidden' | 'open' | 'conduit';
  voltage: 220 | 380;
  derating?: DeratingFactors;
}

export interface ComponentResult {
  cableSection: string; // mm2
  breakerRating: string; // Amps
  voltageDrop: number; // %
  isCompliant: boolean;
  deratedCurrentCapacity: number; // Max Amps allowed for cable with factors
}

// Floor Plan Types
export type ElementType = 'socket' | 'switch' | 'light' | 'db' | 'appliance' | 'door' | 'window';

export interface PlanElement {
  id: string;
  type: ElementType;
  x: number; // percentage 0-100
  y: number; // percentage 0-100
  rotation?: number; // degrees 0, 90, 180, 270
  mountingHeight?: number; // cm from floor (Z-axis)
  label?: string;
  circuitId?: string; // Group assignment e.g. "Gr-1"
  power?: number; // kW for voltage drop calc
  phase?: 'L1' | 'L2' | 'L3'; // For coloring and calculation
  lumens?: number; // Luminous flux for lighting calc
  loadId?: string; // ID referencing LoadItem
}

export interface Wall {
  id: string;
  x1: number; // percentage
  y1: number; // percentage
  x2: number; // percentage
  y2: number; // percentage
  thickness: number; // pixels (visual)
}

export interface CableRun {
  id: string;
  fromId: string;
  toId: string;
  type: 'power' | 'light';
  length: number; // calculated meters (including vertical drops)
  points?: {x: number, y: number}[]; // Optional custom waypoints
}

export interface RoomLayoutRequest {
  roomType: string;
  width: number; // meters
  length: number; // meters
}

export interface LayoutGenerationResult {
  elements: PlanElement[];
  reasoning: string;
}

// Panel Schedule Types
export type ModuleType = 'breaker_1p' | 'breaker_2p' | 'breaker_3p' | 'rcd' | 'diff' | 'switch_3p' | 'meter' | 'relay';

export interface PanelModule {
  id: string;
  type: ModuleType;
  name: string;
  rating: string; // e.g. "16A", "40A 30mA"
  width: number; // standard 17.5mm modules count
  color?: string; // for visualization hints
}

export type BusbarType = 'comb_3p' | 'L1' | 'L2' | 'L3';

export interface PanelRow {
  id: string;
  modules: PanelModule[];
  busType?: BusbarType; // Default to comb_3p
}

export interface PanelConfig {
  rows: PanelRow[];
  enclosureSize: number; // Total modules capacity
}

// Reports & Spec Types
export type MaterialTier = 'budget' | 'standard' | 'premium';

export interface SpecificationItem {
  id: string;
  category: 'Equipment' | 'Cable' | 'Wiring' | 'Protection' | 'Consumables' | 'Services'; // Added Services
  name: string;
  model?: string;
  unit: string;
  quantity: number;
  estimatedPrice?: number; // RUB
  isAutoGenerated?: boolean; // Flag to identify items created by calculator
}

export interface ProjectAuditResult {
  score: number; // 0-100
  missingItems: string[];
  optimizations: string[];
  summary: string;
}

export interface RoomDimensions {
  width: number; // meters
  length: number; // meters
  ceilingHeight: number; // meters (default 2.7)
}

export interface ProjectMetadata {
  clientName: string;
  projectAddress: string;
  designerName: string;
  projectDate: string;
  projectStage: 'ЭП' | 'РД'; // Sketch or Working Docs
  projectCode: string;
}

// Visual Settings
export type ViewMode = 'default' | 'phase' | 'circuit' | 'voltage';

export interface LayerConfig {
  walls: boolean;
  arch: boolean; // Doors/Windows
  devices: boolean;
  cables: boolean;
  labels: boolean;
}

// Global Context Type
export interface ProjectContextType {
  projectName: string;
  setProjectName: (name: string) => void;
  
  metadata: ProjectMetadata;
  setMetadata: (meta: ProjectMetadata) => void;

  // Data
  loads: LoadItem[];
  setLoads: (loads: LoadItem[]) => void;
  updateLoadPhase: (id: string, phase: 'L1' | 'L2' | 'L3' | 'ABC') => void;
  
  panelConfig: PanelConfig | null;
  setPanelConfig: (config: PanelConfig) => void;
  
  floorPlanElements: PlanElement[];
  setFloorPlanElements: (elements: PlanElement[]) => void;

  walls: Wall[];
  setWalls: (walls: Wall[]) => void;

  cableRuns: CableRun[];
  setCableRuns: (runs: CableRun[]) => void;

  floorPlanBackgroundImage: string | null;
  setFloorPlanBackgroundImage: (dataUrl: string | null) => void;

  roomDimensions: RoomDimensions;
  setRoomDimensions: (dims: RoomDimensions) => void;
  
  specification: SpecificationItem[];
  setSpecification: (items: SpecificationItem[]) => void;
  addToSpecification: (items: SpecificationItem[]) => void;
  updateSpecificationItem: (id: string, updates: Partial<SpecificationItem>) => void;
  clearSpecification: () => void;

  // Domain Actions
  renameCircuit: (oldName: string, newName: string) => void;

  // Persistence
  exportProject: () => string;
  importProject: (json: string) => boolean;
  resetProject: () => void;
}
